import "./globals.css";
import { Noto_Sans_Lao_Looped } from "next/font/google";

import { NavBar, Footer } from "@/components";

const notoSansLooped = Noto_Sans_Lao_Looped({ subsets: ["latin"] });

export const metadata = {
  title: "ສະພາປະຊາຊົນ ແຂວງຄຳມ່ວນ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSansLooped.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
