import "./globals.css";
import { Noto_Serif_Lao } from "next/font/google";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const notoSerifLao = Noto_Serif_Lao({ subsets: ["latin"] });

export const metadata = {
  title: "ສະພາປະຊາຊົນ ແຂວງຄຳມ່ວນ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSerifLao.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
